config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :events do
    resources :tickets, only: [:new, :create, :destroy]
  end

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date >= ?", Time.now) }

  belongs_to :creator, class_name: "User"
  has_many :tickets
  has_many :attendees, through: :tickets, source: :attendee
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :attendee, class_name: "User", foreign_key: "attendee_id"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { minimum: 3 }

  has_many :created_events, class_name: "Event", foreign_key: "creator_id"
  has_many :tickets, foreign_key: "attendee_id"
  has_many :attended_events, through: :tickets, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  def index
    @events = Event.order(date: :asc)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "Event '#{@event.name}' created!"
      redirect_to @event
    else
      flash[:alert] = "Some error!"
      render "new"
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    if @event.attendees.include?(current_user)
      flash[:error] = "You are already attending this event."
      redirect_to root_path
    else
      @ticket = Ticket.new
    end
  end

  def create
    @event = Event.find(params[:event_id])

    if current_user == @event.creator
      flash[:error] = "You cannot purchase a ticket for your own event."
      redirect_to root_path
    else
      @ticket = current_user.tickets.build(event: @event)

      if @ticket.save
        flash[:success] = "Ticket purchase was successful."
        redirect_to root_path
      else
        flash[:error] = "Error purchasing the ticket."
        render "new"
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @events = current_user.created_events
    @attended_events = current_user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:name, :date, :location)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date.strftime("%d %b %Y, %I:%M %p") %></td>
        <td><%= event.location %></td>
        <td>
          <% if user_signed_in? %>
            <% if event.creator == current_user %>
              Organizer
            <% else %>
              <%= link_to "Attend Event", new_event_ticket_path(event) %>
            <% end %>
          <% else %>
            <%= link_to "Log in to Attend", new_user_session_path %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New event</h1>
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :name %><br/>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :location %><br/>
    <%= form.text_field :location %>
  </div>
  <div>
    <%= form.label :date %><br/>
    <%= form.date_field :date %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<br/>
<%= @event.date.strftime("%d %b %Y, %I:%M %p") %>
<br/>
<%= @event.location %>
<br/>
<p>Attendees</p>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
    <br/>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@picocss/pico@next/css/pico.min.css"
    />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="container">
      <ul>
        <li><%= link_to "Private Events", root_path %></li>
      </ul>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "My Events", current_user %></li>
          <li><%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= button_to "Sign in", new_user_session_path %>
        <% end %>
      </ul>
    </nav>


    <div class="container">
      <% flash.each do |type, msg| %>
        <div><%= msg %></div>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tickets/new.html.erb
<h1>Purchase Ticket</h1>

<%= form_with model: @ticket, url: event_tickets_path(@event) do |form| %>
  <div class="actions">
    <%= form.submit "Purchase Ticket", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>My Events</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>Action</th>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.date.strftime("%d %b %Y, %I:%M %p") %></td>
      <td><%= event.location %></td>
      <td>
        <% if user_signed_in? %>
          <% if event.creator == current_user %>
            Organizer
          <% else %>
            <%= link_to "Attend Event", new_event_ticket_path(event) %>
          <% end %>
        <% else %>
          <%= link_to "Log in to Attend", new_user_session_path %>
        <% end %>
      </td>
    </tr>
  <% end %>

  <% @attended_events.upcoming.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.date.strftime("%d %b %Y, %I:%M %p") %></td>
      <td><%= event.location %></td>
      <td>Attending</td>
    </tr>
  <% end %>
  <% @attended_events.past.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.date.strftime("%d %b %Y, %I:%M %p") %></td>
      <td><%= event.location %></td>
      <td>Attended</td>
    </tr>
  <% end %>
</table>